# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    alfresco:
        build:
          context: ./alfresco
          args:
            ALFRESCO_TAG: ${ALFRESCO_CE_TAG}
            DB: mariadb
        mem_limit: 4416m
        depends_on:  
            - mariadb 
        environment:
            JAVA_OPTS : '
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco 
                -Ddb.driver=com.mysql.cj.jdbc.Driver
                -Ddb.url=jdbc:mysql://mariadb/alfresco?useUnicode=yes\&characterEncoding=UTF-8 

                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Dshare.host=127.0.0.1
                -Dshare.port=8080
                -Dalfresco.host=localhost
                -Dalfresco.port=8080
                -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
                -Dmessaging.broker.url=\"failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true\"
                -Ddeployment.method=DOCKER_COMPOSE
                -Dtransform.service.enabled=true
                -Dtransform.service.url=http://transform-router:8095
                -Dsfs.url=http://shared-file-store:8099/
                -Dlocal.transform.service.enabled=true
                -DlocalTransform.pdfrenderer.url=http://alfresco-pdf-renderer:8090/
                -DlocalTransform.imagemagick.url=http://imagemagick:8090/
                -DlocalTransform.libreoffice.url=http://libreoffice:8090/
                -DlocalTransform.tika.url=http://tika:8090/
                -DlocalTransform.misc.url=http://transform-misc:8090/
                -Dlegacy.transform.service.enabled=true
                -Dalfresco-pdf-renderer.url=http://alfresco-pdf-renderer:8090/
                -Djodconverter.url=http://libreoffice:8090/
                -Dimg.url=http://imagemagick:8090/
                -Dtika.url=http://tika:8090/
                -Dtransform.misc.url=http://transform-misc:8090/

                -Dcsrf.filter.enabled=false
                -Ddsync.service.uris=http://localhost:9090/alfresco

                -XX:+UseG1GC -XX:+UseStringDeduplication
                -Xms3904m -Xmx3904m   
            '
        volumes:
            - ./data/alf-repo-data:/usr/local/tomcat/alf_data
            - ./logs/alfresco:/usr/local/tomcat/logs 
        

    alfresco-pdf-renderer:
        image: alfresco/alfresco-pdf-renderer:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8090:8090
        links:
        - activemq

    imagemagick:
        image: alfresco/alfresco-imagemagick:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8091:8090
        links:
        - activemq

    libreoffice:
        image: alfresco/alfresco-libreoffice:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8092:8090
        links:
        - activemq

    tika:
        image: alfresco/alfresco-tika:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8093:8090
        links:
            - activemq

    transform-misc:
        image: alfresco/alfresco-transform-misc:2.1.1
        mem_limit: 1g
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            ACTIVEMQ_URL: "nio://activemq:61616"
            FILE_STORE_URL: "http://shared-file-store:8099/alfresco/api/-default-/private/sfs/versions/1/file"
        ports:
            - 8094:8090
        links:
            - activemq

    shared-file-store:
        image: alfresco/alfresco-shared-file-store:0.5.3
        mem_limit: 512m
        environment:
            JAVA_OPTS: " -Xms256m -Xmx512m"
            scheduler.content.age.millis: 86400000
            scheduler.cleanup.interval: 86400000
        ports:
            - 8099:8099
        volumes:
            - shared-file-store-volume:/tmp/Alfresco/sfs

    share:
        build:
          context: ./share
          args:
            SHARE_TAG: ${SHARE_TAG}
        mem_limit: 1104m
        environment:
            REPO_HOST: "alfresco"
            REPO_PORT: "8080"
            JAVA_OPTS: "
                -Xms976m -Xmx976m
                -Dalfresco.context=alfresco
                -Dalfresco.protocol=http
                "
        volumes:
            - ./logs/share:/usr/local/tomcat/logs

     
    mariadb:
        image: mariadb:latest
        mem_limit: 1104m
        environment:
            - MYSQL_ROOT_PASSWORD=alfresco
            - MYSQL_DATABASE=alfresco
            - MYSQL_USER=alfresco
            - MYSQL_PASSWORD=alfresco
        command: "mysqld
            --character-set-server=utf8
            --collation-server=utf8_bin
            --lower_case_table_names=1
            --max_connections=200
            --innodb-flush-method=O_DIRECT
            --wait_timeout=28800"
        volumes:
            - ./data/mariadb_data:/var/lib/mysql
            - ./logs/mariadb:/var/log/mysql
        ports:
            - 3306:3306
    

    solr6:
        build:
          context: ./search
          args:
            SEARCH_TAG: $SEARCH_CE_TAG
            SOLR_HOSTNAME: solr6
            ALFRESCO_HOSTNAME: alfresco
            ALFRESCO_COMMS: none
            CROSS_LOCALE: "false"
        mem_limit: 2208m
        environment:
            #Solr needs to know how to register itself with Alfresco
            SOLR_ALFRESCO_HOST: "alfresco"
            SOLR_ALFRESCO_PORT: "8080"
            #Alfresco needs to know how to call solr
            SOLR_SOLR_HOST: "solr6"
            SOLR_SOLR_PORT: "8983"
            #Create the default alfresco and archive cores
            SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
            SOLR_JAVA_MEM: "-Xms1952m -Xmx1952m"
            SOLR_OPTS: "
                -XX:NewSize=848m
                -XX:MaxNewSize=848m
            "
        volumes:
            - ./data/solr-data:/opt/alfresco-search-services/data

    activemq:
        image: alfresco/alfresco-activemq:5.15.8
        mem_limit: 1g
        ports:
            - 8161:8161 # Web Console
            - 5672:5672 # AMQP
            - 61616:61616 # OpenWire
            - 61613:61613 # STOMP

    digital-workspace:
        image: quay.io/alfresco/alfresco-digital-workspace:1.4.0
        mem_limit: 128m
        environment:
            BASE_PATH: ./

    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: alfresco/alfresco-acs-nginx:3.0.1
        mem_limit: 128m
        depends_on:
            - alfresco
            - digital-workspace
        volumes:
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            # - ./config/nginx.htpasswd:/etc/nginx/conf.d/nginx.htpasswd 
            # - ./config/cert/localhost.cer:/etc/nginx/localhost.cer
            # - ./config/cert/localhost.key:/etc/nginx/localhost.key 
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco
            - share

    sync-service:
        image: quay.io/alfresco/service-sync:3.3.1
        mem_limit: 1g
        environment:
            JAVA_OPTS : "
            -Dsql.db.driver=org.postgresql.Driver
            -Dsql.db.url=jdbc:postgresql://postgres:5432/alfresco
            -Dsql.db.username=alfresco
            -Dsql.db.password=alfresco
            -Dmessaging.broker.host=activemq
            -Drepo.hostname=alfresco
            -Drepo.port=8080
            -Ddw.server.applicationConnectors[0].type=http
            -Xms1000m -Xmx1000m
            "

        ports:
            - 9090:9090

volumes:
    shared-file-store-volume:
        driver_opts:
            type: tmpfs
            device: tmpfs

    

    

    
