# Using version 2 as 3 does not support resource constraint options (cpu_*, mem_* limits) for non swarm mode in Compose
version: "2"

services:
    
    # HTTP proxy to provide HTTP Default port access to services
    # SOLR API and SOLR Web Console are protected to avoid unauthenticated access
    proxy:
        image: alfresco/alfresco-acs-nginx:3.0.1
        mem_limit: 128m
        volumes:
            - ./config/nginxProxy.conf:/etc/nginx/nginx-Proxy.conf
        ports:
            - 8080:8080
        links:
            - digital-workspace
            - alfresco
            - share
            - process
            - process-admin
    
